# geocalculs.pyi
# Ce fichier définit l'interface publique de la bibliothèque pour l'autocomplétion.

from typing import List, Tuple, Union, Any

# Définition d'un type générique pour toutes les formes géométriques
Shape = Union['Carre', 'Rectangle', 'Cercle', 'Triangle', 'Losange', 'Polygone']

# ==========================================
# 1. CLASSES GÉOMÉTRIQUES
# ==========================================

class Point:
    x: float
    y: float
    def __init__(self, x: float, y: float): ...

class AABB:
    min_x: float
    min_y: float
    max_x: float
    max_y: float
    def __init__(self, p1: Point, p2: Point): ...
    def contains(self, p: Point) -> bool: ...

class Carre:
    x: float
    y: float
    cote: float
    def __init__(self, x: float, y: float, cote: float): ...
    def perimetre(self) -> float: ...
    def surface(self) -> float: ...

class Rectangle:
    x: float
    y: float
    largeur: float
    hauteur: float
    def __init__(self, x: float, y: float, largeur: float, hauteur: float): ...
    def perimetre(self) -> float: ...
    def surface(self) -> float: ...

class Cercle:
    centre_x: float
    centre_y: float
    rayon: float
    def __init__(self, centre_x: float, centre_y: float, rayon: float): ...
    def perimetre(self) -> float: ...
    def surface(self) -> float: ...

class Triangle:
    ax: float
    ay: float
    bx: float
    by: float
    cx: float
    cy: float
    def __init__(self, ax: float, ay: float, bx: float, by: float, cx: float, cy: float): ...
    def perimetre(self) -> float: ...
    def surface(self) -> float: ...

class Losange:
    x: float
    y: float
    largeur: float
    hauteur: float
    def __init__(self, x: float, y: float, largeur: float, hauteur: float): ...
    def perimetre(self) -> float: ...
    def surface(self) -> float: ...
    def description(self) -> str: ...

class Polygone:
    points: List[Tuple[float, float]]
    def __init__(self, points: List[Tuple[float, float]]): ...
    def perimetre(self) -> float: ...
    def surface(self) -> float: ...
    def nombre_de_sommets(self) -> int: ...

# ==========================================
# 2. FONCTIONS UTILITAIRES & MATHS
# ==========================================

def distance_2d(x1: float, y1: float, x2: float, y2: float) -> float: ...

def definir_rectangle(x: float, y: float, largeur: float, hauteur: float) -> str: ...

def valider_valeurs(values: List[float]) -> bool: ...
def valider_triangle(a: float, b: float, c: float) -> bool: ...

def orientation(a: Point, b: Point, c: Point) -> int: ...
def on_segment(a: Point, b: Point, c: Point) -> bool: ...

# Wrappers de calcul simples
def perimetre_rectangle(largeur: float, hauteur: float) -> float: ...
def surface_rectangle(largeur: float, hauteur: float) -> float: ...
def perimetre_triangle(a: float, b: float, c: float) -> float: ...
def surface_triangle(a: float, b: float, c: float) -> float: ...

# ==========================================
# 3. MOTEURS PHYSIQUES (Collision & Inclusion)
# ==========================================

def intersecte(forme_a: Shape, forme_b: Shape, mode: str = "bool") -> bool:
    """
    Vérifie si deux formes géométriques se touchent ou se chevauchent.
    Utilise le théorème SAT et la triangulation pour les polygones concaves.
    """
    ...

def appartient(px: float, py: float, forme: Shape, mode: str = "bord") -> bool:
    """
    Vérifie si un point (px, py) appartient à une forme géométrique.
    Le mode 'bord' (par défaut) inclut les frontières.
    """
    ...

# ==========================================
# 4. FONCTIONS DE DISTANCE (Forme <-> Forme)
# ==========================================

# --- CARRÉ ---
def dist_point_carre(p: Point, c: Carre) -> float: ...
def dist_carre_cercle(c: Carre, cercle: Cercle) -> float: ...
def dist_carre_rectangle(c: Carre, r: Rectangle) -> float: ...
def dist_carre_carre(c1: Carre, c2: Carre) -> float: ...
def dist_carre_triangle(c: Carre, t: Triangle) -> float: ...
def dist_carre_polygone(c: Carre, poly: Polygone) -> float: ...

# --- RECTANGLE ---
def dist_point_rectangle(p: Point, r: Rectangle) -> float: ...
def dist_rect_rect(r1: Rectangle, r2: Rectangle) -> float: ...
def dist_rectangle_carre(r: Rectangle, c: Carre) -> float: ...
def dist_rectangle_cercle(r: Rectangle, c: Cercle) -> float: ...
def dist_rectangle_triangle(r: Rectangle, t: Triangle) -> float: ...
def dist_rectangle_polygone(r: Rectangle, poly: Polygone) -> float: ...

# --- TRIANGLE ---
def dist_point_triangle(p: Point, t: Triangle) -> float: ...
def dist_triangle_rectangle(t: Triangle, r: Rectangle) -> float: ...
def dist_triangle_carre(t: Triangle, c: Carre) -> float: ...
def dist_triangle_cercle(t: Triangle, c: Cercle) -> float: ...
def dist_triangle_triangle(t1: Triangle, t2: Triangle) -> float: ...
def dist_triangle_polygone(t: Triangle, poly: Polygone) -> float: ...

# --- CERCLE ---
def dist_point_cercle(p: Point, c: Cercle) -> float: ...
def dist_cercle_cercle(c1: Cercle, c2: Cercle) -> float: ...
def dist_cercle_rectangle(c: Cercle, r: Rectangle) -> float: ...
def dist_cercle_carre(c: Cercle, car: Carre) -> float: ...
def dist_cercle_triangle(c: Cercle, t: Triangle) -> float: ...
def dist_cercle_polygone(c: Cercle, poly: Polygone) -> float: ...

# --- POLYGONE ---
def dist_point_polygone(p: Point, poly: Polygone) -> float: ...
def dist_poly_poly(p1: Polygone, p2: Polygone) -> float: ...
# Note: Les fonctions inverses (dist_carre_polygone etc.) sont déjà listées plus haut, 
# mais voici celles spécifiques au module polygon_distance si exportées sous ces noms:
# (Dans ton lib.rs, elles semblent mapper vers les mêmes noms, donc c'est couvert)

# --- LOSANGE ---
def dist_point_losange(p: Point, l: Losange) -> float: ...
def dist_losange_cercle(l: Losange, c: Cercle) -> float: ...
def dist_losange_rectangle(l: Losange, r: Rectangle) -> float: ...
def dist_losange_carre(l: Losange, c: Carre) -> float: ...
def dist_losange_triangle(l: Losange, t: Triangle) -> float: ...
def dist_losange_polygone(l: Losange, p: Polygone) -> float: ...
def dist_losange_losange(l1: Losange, l2: Losange) -> float: ...